#!/usr/bin/env python3
"""Regenerate all Milestone 2 (stability/amplification) figures deterministically.

Run with:

    python3 scripts/generate_m2_figures.py

Figures are written to figures/*.png. Regeneration is deterministic: no
randomness is used anywhere in the plotted quantities, and Matplotlib's
Agg backend with fixed figure/DPI settings produces byte-identical PNGs
across repeated runs on the same machine/library versions.

This script does not touch the three Milestone 1 figures (generated by
scripts/generate_figures.py).
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import matplotlib.pyplot as plt

from boundary_layer_transition.external_flow import default_velocity_distribution
from boundary_layer_transition.laminar_bl import solve_thwaites
from boundary_layer_transition.operating_point import GenericSailplaneOperatingPoint, default_operating_point
from boundary_layer_transition.stability import RE_THETA_CRIT_ZPG, solve_amplification

FIGURES_DIR = Path(__file__).resolve().parent.parent / "figures"
DPI = 150

CAVEAT = "Generic reduced-order model — illustrative only, not experimentally validated."
NCRIT_CAVEAT = "No N_crit selected — this figure does not predict transition."

ONSET_COLOR = "#1a7a3c"
SEP_COLOR = "#a83232"
CURVE_COLOR = "#1f5fa8"


def _add_caveat(fig: plt.Figure, extra: str | None = None) -> None:
    text = CAVEAT if extra is None else f"{CAVEAT}\n{extra}"
    fig.text(0.5, 0.010, text, ha="center", va="bottom", fontsize=8.5, style="italic", color="#7a1f1f")


def _mark_onset_and_separation(ax, asol) -> None:
    if asol.onset_s is not None:
        ax.axvline(asol.onset_s, color=ONSET_COLOR, ls="--", lw=1.3)
    ax.axvline(asol.s_sep, color=SEP_COLOR, ls=":", lw=1.3)


def plot_stability_inputs(op, asol) -> None:
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7.6, 6.8), sharex=True)

    valid = asol.valid
    ax1.plot(asol.s[valid], asol.re_theta[valid], color=CURVE_COLOR, lw=2.0, label=r"$Re_\theta(x/c)$")
    ax1.plot(
        asol.s[valid], asol.re_theta_crit[valid], color="0.4", lw=1.5, ls="--",
        label=r"local critical $Re_{\theta}(H)$ (modeled onset criterion)",
    )
    ax1.axhline(RE_THETA_CRIT_ZPG, color="0.75", lw=1.0, ls=":", label=r"Blasius ZPG anchor, $Re_{\theta,crit}=200$")

    ax2.plot(asol.s[valid], asol.h[valid], color=CURVE_COLOR, lw=2.0, label=r"$H(x/c)$")
    ax2b = ax2.twinx()
    ax2b.plot(asol.s[valid], asol.lam[valid], color="#a86b1f", lw=1.6, ls="-.", label=r"$\lambda(x/c)$ (Thwaites)")
    ax2b.set_ylabel(r"$\lambda$", color="#a86b1f")
    ax2b.tick_params(axis="y", colors="#a86b1f")
    ax2b.set_ylim(-0.12, 0.08)

    for ax in (ax1, ax2):
        _mark_onset_and_separation(ax, asol)

    if asol.onset_s is not None:
        ax1.annotate(
            f"modeled instability onset\n$x/c={asol.onset_s:.3f}$",
            xy=(asol.onset_s, RE_THETA_CRIT_ZPG),
            xytext=(asol.onset_s + 0.06, RE_THETA_CRIT_ZPG - 90),
            fontsize=8,
            color=ONSET_COLOR,
            arrowprops=dict(arrowstyle="->", color=ONSET_COLOR, lw=0.8),
        )
    ax1.text(
        asol.s_sep - 0.012, ax1.get_ylim()[1] - 0.03 * (ax1.get_ylim()[1] - ax1.get_ylim()[0]),
        f"M1 laminar-separation diagnostic, $x/c={asol.s_sep:.3f}$ (invalid beyond)",
        rotation=90, va="top", ha="right", fontsize=7.6, color=SEP_COLOR,
    )

    ax1.set_ylabel(r"$Re_\theta$")
    ax1.set_title(
        "Stability Inputs: Momentum-Thickness Reynolds Number, Shape Factor, and\n"
        r"Thwaites Pressure-Gradient Parameter vs. $x/c$"
    )
    ax1.legend(loc="upper left", fontsize=8, frameon=True)
    ax1.grid(alpha=0.25)

    ax2.set_xlabel(r"nondimensional chordwise coordinate, $x/c$")
    ax2.set_ylabel(r"shape factor, $H$")
    lines2a, labels2a = ax2.get_legend_handles_labels()
    lines2b, labels2b = ax2b.get_legend_handles_labels()
    ax2.legend(lines2a + lines2b, labels2a + labels2b, loc="upper left", fontsize=8, frameon=True)
    ax2.grid(alpha=0.25)
    ax2.set_xlim(0.0, min(1.0, asol.s_sep * 1.15))

    fig.subplots_adjust(left=0.11, right=0.90, top=0.90, bottom=0.10, hspace=0.08)
    _add_caveat(fig)
    fig.savefig(FIGURES_DIR / "stability_inputs.png", dpi=DPI)
    plt.close(fig)


def plot_n_factor_growth(op, asol) -> None:
    fig, ax = plt.subplots(figsize=(7.6, 5.2))

    valid = asol.valid
    ax.plot(asol.s[valid], asol.n[valid], color=CURVE_COLOR, lw=2.2, label=r"$N(x/c)$")

    if asol.onset_s is not None:
        ax.axvline(asol.onset_s, color=ONSET_COLOR, ls="--", lw=1.4)
        ax.annotate(
            f"modeled instability onset\n$x/c={asol.onset_s:.3f}$, $N=0$",
            xy=(asol.onset_s, 0.0),
            xytext=(asol.onset_s + 0.03, asol.n_max * 0.55),
            fontsize=8.5,
            color=ONSET_COLOR,
            arrowprops=dict(arrowstyle="->", color=ONSET_COLOR, lw=0.8),
        )
        ax.axvspan(asol.onset_s, asol.s_sep, color=ONSET_COLOR, alpha=0.05)
        ax.text(
            (asol.onset_s + asol.s_sep) / 2, asol.n_max * 1.04,
            "amplification-active region", ha="center", fontsize=8, color=ONSET_COLOR,
        )

    ax.axvline(asol.s_sep, color=SEP_COLOR, ls=":", lw=1.4)
    ax.annotate(
        f"M1 laminar-separation diagnostic\n$x/c={asol.s_sep:.3f}$ (N not tracked beyond)",
        xy=(asol.s_sep, asol.n_max),
        xytext=(asol.s_sep - 0.34, asol.n_max * 0.75),
        fontsize=8,
        color=SEP_COLOR,
        arrowprops=dict(arrowstyle="->", color=SEP_COLOR, lw=0.8),
    )

    ax.set_xlabel(r"nondimensional chordwise coordinate, $x/c$")
    ax.set_ylabel(r"amplification factor, $N = \ln(A/A_0)$")
    ax.set_title(
        "e^N Amplification-Factor Growth (reduced-order proxy)\n" + NCRIT_CAVEAT
    )
    ax.set_xlim(0.0, min(1.0, asol.s_sep * 1.15))
    ax.set_ylim(0.0, asol.n_max * 1.22)
    ax.legend(loc="upper left", fontsize=9, frameon=True)
    ax.grid(alpha=0.25)
    fig.subplots_adjust(left=0.11, right=0.97, top=0.85, bottom=0.13)
    _add_caveat(fig)
    fig.savefig(FIGURES_DIR / "n_factor_growth.png", dpi=DPI)
    plt.close(fig)


def plot_reynolds_sensitivity() -> None:
    base = default_operating_point()
    v_infs = [20.0, 25.0, 30.0]
    colors = ["#5aa2d8", CURVE_COLOR, "#123a63"]

    fig, ax = plt.subplots(figsize=(7.6, 5.2))
    s_sep_common = None
    n_max_overall = 0.0

    for v_inf, color in zip(v_infs, colors, strict=True):
        op_v = GenericSailplaneOperatingPoint(
            chord_m=base.chord_m,
            v_inf_mps=v_inf,
            rho_kgm3=base.rho_kgm3,
            mu_pas=base.mu_pas,
            temperature_k=base.temperature_k,
            alpha_deg=base.alpha_deg,
        )
        dist_v = default_velocity_distribution(op_v.chord_m, op_v.v_inf_mps)
        tsol_v = solve_thwaites(dist_v, op_v.nu_m2s, n_points=4001)
        asol_v = solve_amplification(op_v, tsol_v)
        valid = asol_v.valid
        ax.plot(
            asol_v.s[valid], asol_v.n[valid], color=color, lw=2.0,
            label=rf"$V_\infty={v_inf:.0f}$ m/s, $Re_c={op_v.re_c:.2e}$",
        )
        s_sep_common = asol_v.s_sep
        n_max_overall = max(n_max_overall, asol_v.n_max)

    if s_sep_common is not None:
        ax.axvline(s_sep_common, color=SEP_COLOR, ls=":", lw=1.3)
        ax.text(
            s_sep_common - 0.01, n_max_overall * 0.5,
            f"common laminar-separation\ndiagnostic, $x/c \\approx {s_sep_common:.3f}$",
            rotation=90, va="center", ha="right", fontsize=7.8, color=SEP_COLOR,
        )

    ax.set_xlabel(r"nondimensional chordwise coordinate, $x/c$")
    ax.set_ylabel(r"amplification factor, $N = \ln(A/A_0)$")
    ax.set_title(
        r"$Re_c$ Sensitivity of the N-Factor Curve ($V_\infty$ varied, $U_e/V_\infty(x/c)$ shape fixed)"
        "\n" + NCRIT_CAVEAT
    )
    ax.set_xlim(0.0, min(1.0, (s_sep_common or 0.5) * 1.15))
    ax.set_ylim(0.0, n_max_overall * 1.2)
    ax.legend(loc="upper left", fontsize=8.5, frameon=True)
    ax.grid(alpha=0.25)
    fig.subplots_adjust(left=0.11, right=0.97, top=0.84, bottom=0.13)
    _add_caveat(fig)
    fig.savefig(FIGURES_DIR / "n_factor_reynolds_sensitivity.png", dpi=DPI)
    plt.close(fig)


def main() -> None:
    FIGURES_DIR.mkdir(exist_ok=True)
    op = default_operating_point()
    dist = default_velocity_distribution(op.chord_m, op.v_inf_mps)
    tsol = solve_thwaites(dist, op.nu_m2s, n_points=4001)
    asol = solve_amplification(op, tsol)

    plot_stability_inputs(op, asol)
    plot_n_factor_growth(op, asol)
    plot_reynolds_sensitivity()
    print(f"Wrote Milestone 2 figures to {FIGURES_DIR}")


if __name__ == "__main__":
    main()
